//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Resources.Reso" +
                            "urce", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not find file &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string CannotFindFile {
            get {
                return ResourceManager.GetString("CannotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The parameter should not be null or empty. ähnelt.
        /// </summary>
        internal static string Common_CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Common_CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test Run deployment issue: Bad deployment item: &apos;{0}&apos;: output directory &apos;{1}&apos; specifies the item to be deployed outside deployment root directory which is not allowed. ähnelt.
        /// </summary>
        internal static string DeploymentErrorBadDeploymentItem {
            get {
                return ResourceManager.GetString("DeploymentErrorBadDeploymentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test Run deployment issue: Failed to access output directory &apos;{1}&apos; specified by deployment item &apos;{0}&apos;, the item will not be deployed: {2}: {3} ähnelt.
        /// </summary>
        internal static string DeploymentErrorFailedToAccesOutputDirectory {
            get {
                return ResourceManager.GetString("DeploymentErrorFailedToAccesOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test Run deployment issue: Failed to access the file &apos;{0}&apos;: {1}: {2} ähnelt.
        /// </summary>
        internal static string DeploymentErrorFailedToAccessFile {
            get {
                return ResourceManager.GetString("DeploymentErrorFailedToAccessFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test Run deployment issue: Failed to copy file &apos;{0}&apos; to &apos;{1}&apos;: {2}: {3} ähnelt.
        /// </summary>
        internal static string DeploymentErrorFailedToCopyWithOverwrite {
            get {
                return ResourceManager.GetString("DeploymentErrorFailedToCopyWithOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test Run deployment issue: Failed to deploy dependencies for test storage &apos;{0}&apos;: {1} ähnelt.
        /// </summary>
        internal static string DeploymentErrorFailedToDeployDependencies {
            get {
                return ResourceManager.GetString("DeploymentErrorFailedToDeployDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test Run deployment issue: Failed to get the file for {0}: {1}: {2} ähnelt.
        /// </summary>
        internal static string DeploymentErrorFailedToGetFileForDeploymentItem {
            get {
                return ResourceManager.GetString("DeploymentErrorFailedToGetFileForDeploymentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test Run deployment issue: an error occurred while getting satellite assemblies for {0}: {1}: {2} ähnelt.
        /// </summary>
        internal static string DeploymentErrorGettingSatellite {
            get {
                return ResourceManager.GetString("DeploymentErrorGettingSatellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die deployment item &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string DeploymentItem {
            get {
                return ResourceManager.GetString("DeploymentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid deployment item: the specified path &apos;{0}&apos; or output directory &apos;{1}&apos; contains illegal characters. ähnelt.
        /// </summary>
        internal static string DeploymentItemContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("DeploymentItemContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid deployment item: the output directory cannot be null. ähnelt.
        /// </summary>
        internal static string DeploymentItemOutputDirectoryCannotBeNull {
            get {
                return ResourceManager.GetString("DeploymentItemOutputDirectoryCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid deployment item: the specified output directory &apos;{0}&apos; is not relative. ähnelt.
        /// </summary>
        internal static string DeploymentItemOutputDirectoryMustBeRelative {
            get {
                return ResourceManager.GetString("DeploymentItemOutputDirectoryMustBeRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid deployment item: the path must contain at least one character. ähnelt.
        /// </summary>
        internal static string DeploymentItemPathCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("DeploymentItemPathCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die deployment item &apos;{0}&apos; (output directory &apos;{1}&apos;) ähnelt.
        /// </summary>
        internal static string DeploymentItemWithOutputDirectory {
            get {
                return ResourceManager.GetString("DeploymentItemWithOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MSTestAdapter encountered an unexpected element &apos;{0}&apos; in its settings &apos;{1}&apos;. Remove this element and try again. ähnelt.
        /// </summary>
        internal static string InvalidSettingsXmlElement {
            get {
                return ResourceManager.GetString("InvalidSettingsXmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test Run deployment issue: The assembly or module &apos;{0}&apos; was not found. Reason: {1} ähnelt.
        /// </summary>
        internal static string MissingDeploymentDependency {
            get {
                return ResourceManager.GetString("MissingDeploymentDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test Run deployment issue: The assembly or module &apos;{0}&apos; was not found. ähnelt.
        /// </summary>
        internal static string MissingDeploymentDependencyWithoutReason {
            get {
                return ResourceManager.GetString("MissingDeploymentDependencyWithoutReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}_{1}_{2} ähnelt.
        /// </summary>
        internal static string TestRunName {
            get {
                return ResourceManager.GetString("TestRunName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data source &apos;{0}&apos; cannot be found in the test configuration settings ähnelt.
        /// </summary>
        internal static string UTA_DataSourceConfigurationSectionMissing {
            get {
                return ResourceManager.GetString("UTA_DataSourceConfigurationSectionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The unit test adapter failed to connect to the data source or to read the data. For more information on troubleshooting this error, see &quot;Troubleshooting Data-Driven Unit Tests&quot; (http://go.microsoft.com/fwlink/?LinkId=62412) in the MSDN Library. Error details: {0} ähnelt.
        /// </summary>
        internal static string UTA_ErrorDataConnectionFailed {
            get {
                return ResourceManager.GetString("UTA_ErrorDataConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrong number of objects for permutation. Should be greater than zero. ähnelt.
        /// </summary>
        internal static string WrongNumberOfObjects {
            get {
                return ResourceManager.GetString("WrongNumberOfObjects", resourceCulture);
            }
        }
    }
}
